### ISSUE TITLE
NigeriaMRS workflow - Issues with assigning patient identifier

### ISSUE THREAD

**Issue by caniekwe** [nmrs-nigeria/openmrs-module-nigeriaemr#1]
The patient registration module does not allow options to select a patient program and assign appropriate identifier to the patient

**Comment by dkayiwa** [comment]
You could start by taking a look at this: https://wiki.openmrs.org/display/docs/Registration+App+Configuration

**Comment by henryvalentine** [comment]
Further discussions will be done on this by @caniekwe @lisamurie @dkayiwa and @henryvalentine tomorrow.

**Comment by dkayiwa** [comment]
https://github.com/search?l=&q=org%3Aopenmrs+personAddressWithHierarchy&ref=advsearch&type=Code

https://github.com/openmrs/openmrs-module-registrationapp/blob/master/omod/src/main/webapp/fragments/field/personAddressWithHierarchy.gsp

**Comment by gibrilg** [comment]
I will be adding the new JSON registration app to the patient registration page with access based location (optional)

**Comment by JohnboscoJbTech** [comment]
@henryvalentine can you describe the steps taken to resolve this, so that the issue can be closed. Regards

**Comment by henryvalentine** [comment]
This task involves assigning various identifier types to patient depending on the program being enrolled into. I first created a .gsp fragment and a corresponding fragment controller (PatientIdTypeSetterFragmentController) to handle back-end requests. I then added the fragment information in the patient registration page metadata such that at the point of registration, different identifier types can be assigned to a patient and one of them can be set as the preferred identifier type.
But after a review, it was agreed that putting it up on the patient registration page won't be necessary rather, it can be moved to the patient edit view.
But at each of the program pages, a checkbox can be added beside the textbox for capturing the patient's identifier value for that program so as to set that identifier as preferred or not.
To achieve this, I had to go to each of the program forms and added the following script:

<script type="text/javascript">

        var $ = jQuery;

       var path = $(location).attr('pathname').split('/')[1];
        var baseUrl = '/' + path + '/nigeriaemr/PatientIdTypeSetter';

        $(document).ready(function ()
        {
		
		//This function checks if the identifier type for this program is set as preferred for this patient,
		//If yes, it sets the status of the 'preferred' checkbox as checked
            $.ajax({
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                url: baseUrl + "/getIdentifier.action",
                data: { patientId: $('input[name=personId]').val(), identifierType: $('#pref_type').val() },
                cache: false,
                timeout: 600000,
                success: function (r) {
                    if (r.code > 0) {
                        if (r.identifier.length > 0)
                        {
                            if (r.preferred === true)
                            {
                                $('#preferred').prop("checked", 'checked');
                            }
                        }
                    }
                },
                error: function (e) {
                    console.log("ERROR : ", e);
                }
            });

//This does setting an identifier as preferred
            $('#preferred').click(function (e)
            {
                var patientIdentifier = $('input:text', '#identifer-td').eq(0).val();
                if (patientIdentifier) {
                    if (patientIdentifier.trim().length > 0) {
                        var obj = e.target;
                        var isPreferred = false;
                        if ($(obj).prop("checked") == true) {
                            isPreferred = true;
                        }

                        var patientId = $('input[name=personId]').val();
                        var identifierType = $('#pref_type').val();

                        var pid = { patientId: patientId, patientIdentifier: patientIdentifier, identifierType: identifierType, isPreferred: isPreferred };
                        var link = baseUrl  + "/setPidType.action";

                        $.ajax({
                            contentType: "application/json; charset=utf-8",
                            dataType: "json",
                            url: link,
                            data: pid,
                            cache: false,
                            timeout: 600000,
                            success: function (r)
                            {
                                if (r.code !== 5)
                                {
                                    alert(r.message);
                                }
                            },
                            error: function (e)
                            {
                               console.log("ERROR : ", e);
                            }
                        });
                    }
                    else
                    {
                        $('#preferred').prop("checked", '');
                        alert('Please fill in the ART No before setting as preferred');
                    }
                }
                else
                {
                    $('#preferred').prop("checked", '');
                    alert('Please fill in the ART No before setting as preferred');
                }
            });
        });

    </script>
	
	and then adding an id "identifer-td" to the <td> tags housing the Identifier input/textbox so I can access the provided Identifier value:

	<td id="identifer-td">
		<patient default="" required="true" field="identifier" identifierTypeId='4' />
	</td>
	
	I then an accompanying <td> tag as shown below:
	
	 <td style="vertical-align: top;">
		<label> <input type="checkbox" name="preferred" id="preferred" />preferred</label>
		<input type="hidden" name="pref_type" id="pref_type" value="4" />
	</td>

The value of the hidden input which is 4 as shown above is used to hold the identifier type and can be 6, 7, or 8 depending on the program area

At the backend, the function that handles setting the preferred Patient Ientifier Type is:

public @ResponseBody AjaxResponseBody setPidType(@RequestParam(value = "patientId") int patientId, @RequestParam(value = "identifierType") int identifierType, @RequestParam(value = "isPreferred") boolean isPreferred, @RequestParam(value = "patientIdentifier") String patientIdentifier)

I struggled to implement this by passing the parameters as stringified JSON object in the body of a post request but it never worked because the json body cannot be accessed at the controller side as I kept receiving null even after trying with the help of Morris.

We thought initially that if an identifier type is set as preferred for a particular patient, that the value of that identifier will be displayed on the patient information header, but I later realized that an identifier set as preferred for a patient is not what shows on the patient's view header but shows at the patients search page. It becomes the identifier by which a patient can be searched.

In trying to alter the identifier that shows on the patient views header, I realised that Extra entries have to be added via script to the 'metadatamapping_metadata_set_member' table of the database. So, the number of entries (marked as extra patient identifier) in this table ends up showing on the patient views header. The script shown below was used to set PEPFAR Id as part of the Patient Identifiers displayed on the Patient Header:

INSERT INTO metadatamapping_metadata_set_member 
(metadata_set_member_id, metadata_set_id,metadata_class, metadata_uuid, NAME,description,sort_weight,
creator,date_created,retired,UUID)

VALUES(1,1,'org.openmrs.PatientIdentifierType','c82916e4-168c-495f-8ed0-b1b286c30a05','PEPFAR Id', 'PEPFAR Id Assigned at ART Enrolment',1,
2, "2019-09-02",0, 'q82916o4-168c-495f-8ed0-b1y286c30a00'
)

This can be repeated if there is the need to display other IdentifierTypes as well. You just need to change the 4th parameter in the VALUES part of the script to point to the uuid of the needed identifierType. Also, the the first parameter labeled '1' needs to change so as to tally with the number of items (rows) being inserted into the table. The last parameter has to be dynamically generated Global Unique Identifier


The primary identifier type can be changed in the 'metadatamapping_metadata_term_mapping' table by running this script:

UPDATE `metadatamapping_metadata_term_mapping` SET metadata_uuid='fa2752e2-aafc-4b17-8e89-b3e4efd7568e' WHERE `code`= 'emr.primaryIdentifierType'

where metadata_uuid (value gotten from the identifier_type tabel) is the uuid of the required identifierType.
